### PR TITLE
Update 2020.2

### PR DESCRIPTION
**Pull request by bnavigator**
- Copied sources form 2020.2 tarball
  - new GPGMail_5, which lacks the GMSupportPlan extension but needs it.
  - paddle is removed from Libgpgmac
- Update Makefile to copy the GMSupportPlan from GPGMail_4 and try to build GPGMail_5 too

### CODE REVIEW

**Comment by bnavigator** [comment]
Here is the produced GPGMail_5 file, if you want to check. Still unsigned. (#7)

[Free-GPGMail_5.mailbundle.zip](https://github.com/Free-GPGMail/Free-GPGMail/files/5685946/Free-GPGMail_5.mailbundle.zip)

**Comment by bnavigator** [comment]
@bnavigator just tested new built Free-GPGMail_5.mailbundle, after manually adds Supported11.0PluginCompatibilityUUIDs, it could load and decryption works. But activation fails, reports "Support Plan Activation Failed: The entered activation code is invalid. Please check the entered information and try again.".

_Originally posted by @palxex in https://github.com/Free-GPGMail/Free-GPGMail/issues/7#issuecomment-744126837_

**Comment by bnavigator** [comment]
I radically replaced some methods in the "Support Plan Manager" of GPGMail. A component, which they removed from the published source code, but still call in GPGMail_5. I am not sure, if they are really compliant with the GPL here. Anyway, I used the source from GPGMail_4, added some missing attributes and make them all return "Yes you have a valid support plan" no matter how GPG Mail is asking. At least that is the intention. I might have missed some details of the call logic or support plan data structure.

Please test:

- [Free-GPGMail_3.mailbundle.zip](https://github.com/Free-GPGMail/Free-GPGMail/files/5699313/Free-GPGMail_3.mailbundle.zip)
- [Free-GPGMail_4.mailbundle.zip](https://github.com/Free-GPGMail/Free-GPGMail/files/5699316/Free-GPGMail_4.mailbundle.zip)
- [Free-GPGMail_5.mailbundle.zip](https://github.com/Free-GPGMail/Free-GPGMail/files/5699317/Free-GPGMail_5.mailbundle.zip)

or compile yourself from this branch. In case of errors, any logs are appreciated.

Next task will be how to sign the code.

**Comment by bnavigator** [comment]
> after manually adds Supported11.0PluginCompatibilityUUIDs

~~The fact that this and 10.15 are missing from Info.plist let's me doubt that we have the most recent source code. :angry:~~ 
see below

**Comment by palxex** [comment]
Tested Free-GPGMail_5.mailbundle.zip on Big Sur, both encryption and decryption works.
image

**Comment by bnavigator** [comment]
@palxex, you still had to edit Info.plist and you have disabled gatekeeper, right?

**Comment by palxex** [comment]
> @palxex, you still had to edit Info.plist and you have disabled gatekeeper, right?

In fact my test env was a hackintosh with SIP disabled in OpenCore settings... gatekeeper not bother me from the beginning.
For plist you're right, seems the mailbundle was built before the plist changes committed.

**Comment by bnavigator** [comment]
> The fact that this and 10.15 are missing from Info.plist let's me doubt that we have the most recent source code.

In their e-mail to me, GPGTools claims they published the most recent code. They use a seperate Info.plist in their custom non open source plugin wrapper loader. So we need to maintain our own Info.plist for supported mail.app versions. (a6e1a6d)

**Comment by InternalLoss** [comment]
Tried `Free-GPGMail_5.mailbundle.zip` on my Intel MBP on Big Sur 11.2 beta (20D5029f):
When trying to enable, I got a small warning about the plugin: [Imgur](https://imgur.com/xswqMy8) and then got told that it doesn't work with Mail 14.0 [Imgur](https://imgur.com/7dNdLVL)

In Console, I see the line `Plugin compatibility check failed for GPGMailLoader.mailbundle. The plugin's Info.plist must have a Supported11.2PluginCompatibilityUUIDs key whose value is an array of strings that contains the compatibility UUIDs for the supported versions of Mail. The compatibility UUID value is found in the PluginCompatibilityUUID key of Mail's Info.plist`

EDIT: Just to confirm, System Integrity Protection **is** enabled.

**Comment by bnavigator** [comment]
Thanks for the info @InternalLoss 

- The posted Free-GPGMail_5.mailbundle does not have any updated UUIDs in its Info.plist yet. Not for 11.0, 11.1 or 11.2 beta. But you can edit the Info.plist yourself to fix that.
- The images show warning messages about GPGMailLoader.mailbundle. That is not our mailbundle but the custom loader from GPGTools, which I mentioned in https://github.com/Free-GPGMail/Free-GPGMail/pull/10#issuecomment-747434191. You did not do the full replacement procedure. Any hints, where the [ReadMe](https://github.com/Free-GPGMail/Free-GPGMail/blob/update-2020.2/ReadMe.md) should be more concise?

**Comment by InternalLoss** [comment]
That's my fault for not reading properly, however it did come with the same issue - my Mail copy was installed to /Library/Mail/Bundles, so probably just me not properly reading instructions.

Adding the following into the mailbundle made it progress further but since it wasn't signed I wasn't able to test further.
```
	<key>Supported11.2PluginCompatibilityUUIDs</key>
	<array>
		<string>D985F0E4-3BBC-4B95-BBA1-12056AC4A531</string>
	</array>
```

**Comment by bnavigator** [comment]
Thank you. I guess [these updated instructions](https://github.com/Free-GPGMail/Free-GPGMail/pull/8/files?short_path=0b59e9c#diff-0b59e9c9f474883e24cb1319da596e81aa164472c07d90db0df74948792cf6cb) in #8 don't help you either, do they?

**Comment by bnavigator** [comment]
> however it did come with the same issue

Yes, they apparently did not anticipate any usage of GPG Mail on a beta system.

**Comment by InternalLoss** [comment]
I didn't update my GPGTools in a long time - it still has a date from Nov 2019 (I think I deselected it in a previous install - I updated today and there was no option for the Mail plugin). I can confirm disabling Gatekeeper and then enabling it after the plugin was loaded allows it to be ran - I just sent a test signed email to edward@fsf.org and it worked successfully for both signing and decrypting the incoming mail c:

**Comment by bnavigator** [comment]
Just to confirm, that you installed Free-GPG Mail and are not on a trial for the commercial product. You see something similar like https://github.com/Free-GPGMail/Free-GPGMail/pull/10#issuecomment-745798725, right?

**Comment by InternalLoss** [comment]
Sorry, was trying to ad-hoc sign (I'm pretty sure it **requires** notarisation since it throws a notarisation error even after ad-hoc signing) - can confirm that I'm seeing that, and it works once Gatekeeper is re-enabled and Mail.app is restarted! 🎉
Screenshot 2020-12-18 at 17 43 17

**Comment by bnavigator** [comment]
New builds with updated UUIDS and a lot of strings replaced:

- [Free-GPGMail_3.mailbundle.zip](https://github.com/Free-GPGMail/Free-GPGMail/files/5718543/Free-GPGMail_3.mailbundle.zip)
- [Free-GPGMail_4.mailbundle.zip](https://github.com/Free-GPGMail/Free-GPGMail/files/5718544/Free-GPGMail_4.mailbundle.zip)
- [Free-GPGMail_5.mailbundle.zip](https://github.com/Free-GPGMail/Free-GPGMail/files/5718545/Free-GPGMail_5.mailbundle.zip)

**Comment by InternalLoss** [comment]
Just updated to your copy of 5 with Gatekeeper temporarily disabled, worked fine on 11.2 beta c:

**Comment by bnavigator** [comment]
Wow that was fast! :rocket:

**Comment by InternalLoss** [comment]
I check my emails often 🎉

**Comment by sT331h0rs3** [comment]
The latest mentioned `Free-GPGMail_5.mailbundle.zip` works for me (I've tested encryption and decryption).
Big Sur (11.1) + MacBook Air (11-inch, Early 2015).

**Comment by bnavigator** [comment]
Okay. I think I'll merge this, #8 and make a new pre-release. For a "real" release I will need to investigate code-signing more. I created a new Apple-ID, but was not successful in buying a developer account yet.

**Comment by InternalLoss** [comment]
Tested a copy that @oatmealdome had notarised and signed for me - it worked absolutely fine without disabling Gatekeeper and just ran like it's meant to, which is awesome 🎉

**Comment by bnavigator** [comment]
Update:

I just finished a remote session on my boss's Mac. He updated to Big Sur and naturally lost his ability to use Mail.app with GPG Suite. He does not have any development setup. Using the current beta release, installing it into `/Library/Mail/Bundles/` (The user Library in ~/ was locked somehow) and creating a GateKeeper rule with `sudo spctl --add /Library/Mail/Bundles/Free-GPGMail5_5.mailbundle` left him with a working plugin. :tada:

Also, I was finally able to purchase an Apple Developer Subscription. Now I just need to find a way to create signing keys and use those to sign the mailbundle, so that we don't even need the GateKeeper rule. It's not that trivial, if you don't own a Mac. :clown_face:

**Comment by InternalLoss** [comment]
There might be ways to do the signing/notarising of the extension via GitHub Actions, but I could be wrong.

**Comment by bnavigator** [comment]
> There might be ways to do the signing/notarising of the extension via GitHub Actions, but I could be wrong.

Yes there are. But I still need to access a xcode installation on a macOS to create the CSR and keys.

**Comment by InternalLoss** [comment]
Ahhh, okay.

**Comment by bnavigator** [comment]
Github actions fails to build the GPGMail_5 bundle on Big Sur for now: https://github.com/actions/virtual-environments/issues/2486

**Pull request merged**
