### PR TITLE
Update to 2021.3: Free-GPGMail 6.1

### LINKED ISSUE #31: Share from Preview to Mail etc wont work
When I have a PDF opened at Preview and then I signed it and I want to reply with it on Mail it's like Mail gets frozen and the new mail window won't open.
I have tried to restart mail, the thing was exactly the same. Then I've tried to disable Free-GPGMail plugin, mail asked to restart, it restarted and the issue was gone.

So if the plugin is on most of times I cannot use this
Screen Shot 2021-12-13 at 7 52 50 PM
or this
Screen Shot 2021-12-13 at 7 53 06 PM
won't work.

When I disable Free-GPGMail both work..
Thanks in advance!

### LINKED ISSUE #32: Sp3 crashing Arm Mail 12.1
The new Bundle 6sp3 is crashing on 12.1 M1 Max when trying to draft a new email or reply to an existing one. Mail loads fine and decrypts the message with no issue but any action after causes a sigexec crash.

### LINKED ISSUE #38: GPG-suite 2021.3 update?
Has Free-GPGmail been updated with GPG-suite 2021.3 code base?

### PR DESCRIPTION
**Pull request by bnavigator**
Now that GPGTools finally released the source code, (thanks @walterrowe), here is the update for Free-GPGMail.

Closes #38

This should also fix:
 - #31 (I tested it in my Monterey Hackintosh VM)
 - #32 (Please test @nickkilla, @gramels)

This also includes some further string changes in order to remove references and hyperlinks to the GPG Suite. As this is a non-commercial effort, we are not in danger of trademark violations, but of course we do not want anyone to confuse *GPG Mail* with *Free-GPGMail*.

GPG Mail version 3 to 5 were not changed in 2021.3

Test bundle for Free-GPGMail 6.1: 
- [Free-GPGMail_6.1_2021.3.mailbundle.zip](https://github.com/Free-GPGMail/Free-GPGMail/files/7799047/Free-GPGMail_6.1_2021.3.mailbundle.zip)
- Debug symbols: [Free-GPGMail_6.1_2021.3.mailbundle.dSYM.zip](https://github.com/Free-GPGMail/Free-GPGMail/files/7799048/Free-GPGMail_6.1_2021.3.mailbundle.dSYM.zip)

### CODE REVIEW

**Comment by walterrowe** [comment]
I confirm it fixes #31. It also fixes another problem I had not yet reported (having to press keyboard shortcuts twice in Mail).

**Comment by walterrowe** [comment]
It does not appear to address #34 . If you provide me a private email address, I can send you the raw email I received from Facebook so you can determine whether Facebook improperly formatted it vs Free-GPGmail improperly handled the rich text.

**Comment by bnavigator** [comment]
You can send it to code-freegpgmail@bnavigator.de

**Comment by alephc1** [comment]
splendid!

**Comment by nickkilla** [comment]
@bnavigator Can confirm it fixed #32

**Pull request merged**
