### PR TITLE
Update to 2021.1

### LINKED ISSUE #17: GPG Mail 5.1 in GPG Suite 2021.1
Binaries for GPG Suite 2021.1 have been released in May 2021. A few (?) days later, they also started to provide a [tarball](https://releases.gpgtools.org/GPG_Suite-2021.1_105.txz), supposedly providing the source code. In violation of the GPL, this tarball does not include (yet) the sources of GPG Mail 5.1.

Until we have some source code, there is no chance to update Free-GPGMail to 2021.1 including GPG Mail 5.1. :disappointed:

### PR DESCRIPTION
**Pull request by bnavigator**
Fixes #17

### CODE REVIEW

**Comment by bnavigator** [comment]
GHA macos-11 runner is still disabled :(

**Comment by intra-au** [comment]
GPGMail_5 doesn't compile from this branch. I've overwritten files in GMNoSupportPlan folder with the ones from 'master' and it works well.

**Comment by bnavigator** [comment]
Thanks, there was still an error in the slightly modified GMNoSupportPlan sources.

New bundles for testing:
[Free-GPGMail_3.mailbundle.zip](https://github.com/Free-GPGMail/Free-GPGMail/files/7192111/Free-GPGMail_3.mailbundle.zip)
[Free-GPGMail_4.mailbundle.zip](https://github.com/Free-GPGMail/Free-GPGMail/files/7192113/Free-GPGMail_4.mailbundle.zip)
[Free-GPGMail_5.mailbundle.zip](https://github.com/Free-GPGMail/Free-GPGMail/files/7192112/Free-GPGMail_5.mailbundle.zip)

**Comment by bnavigator** [comment]
I have sucessfully installed the GPGMail_5.mailbundle on an OSX-KVM machine running Big Sur :tada:

**Comment by austinhuang0131** [comment]
can confirm that 5 works on a mojave

**Pull request merged**
