### PR TITLE
Update to 2022.2

### LINKED ISSUE #63: Ventura Beta 9 Crashes when saving a draft
To replicate I just start a new email (signing enabled by default), and click cmd+s and mail instantly crashes. 

If I unselect signing by clicking the signing icon, and then cmd+s to save the draft then mail doesn't crash :-( 

If I start a new email, and click the padlock to enable encryption, the signing already enabled by default, and then cmd+s to save then mail DOESNT crash. 

If I start an email, with signing enabled by default, and sending it quickly before the first auto-save happens - then I can send the mail and it doesn't crash. 

I can read signed emails without a crash. 

Some things from console. Meaningless to me :) 

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString characterAtIndex:]: Range or index out of bounds'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001a9ee0458 __exceptionPreprocess + 176
	1   libobjc.A.dylib                     0x00000001a9a2aea8 objc_exception_throw + 60
	2   CoreFoundation                      0x00000001a9fc5ce0 -[__NSCFString characterAtIndex:].cold.1 + 0
	3   CoreFoundation                      0x00000001a9fc5d14 -[__NSCFString getCharacters:range:].cold.1 + 0
	4   CoreFoundation                      0x00000001a9e42d74 -[__NSCFString characterAtIndex:] + 124
	5   Free-GPGMail                        0x0000000110d5d45c Free-GPGMail + 218204
	6   Free-GPGMail                        0x0000000110d5e084 Free-GPGMail + 221316
	7   Mail                                0x00000001047f382c Mail + 636972
	8   Mail                                0x0000000104802a90 Mail + 699024
	9   Mail                           <…>
```

```
(
	0   CoreFoundation                      0x00000001a9ee0458 __exceptionPreprocess + 176
	1   libobjc.A.dylib                     0x00000001a9a2aea8 objc_exception_throw + 60
	2   CoreFoundation                      0x00000001a9fc5ce0 -[__NSCFString characterAtIndex:].cold.1 + 0
	3   CoreFoundation                      0x00000001a9fc5d14 -[__NSCFString getCharacters:range:].cold.1 + 0
	4   CoreFoundation                      0x00000001a9e42d74 -[__NSCFString characterAtIndex:] + 124
	5   Free-GPGMail                        0x0000000110d5d45c Free-GPGMail + 218204
	6   Free-GPGMail                        0x0000000110d5e084 Free-GPGMail + 221316
	7   Mail                                0x00000001047f382c Mail + 636972
	8   Mail                                0x0000000104802a90 Mail + 699024
	9   Mail                                0x00000001048026dc Mail + 698076
	10  Foundation                          0x00000001aad4e350 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 24
	11  Foundation                          0x00000001aad4e210 -[NSBlockOperation main] + 104
	12  Foundation                          0x00000001aad4e1a0 __NSOPERATION_IS_INVOKING_MAIN__ + 16
	13  Foundation                          0x00000001aad4d5b8 -[NSOperation start] + 708
	14  Foundation                          0x00000001aad4d2ec __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 16
	15  Foundation                          0x00000001aad4d1dc __NSOQSchedule_f + 172
	16  libdispatch.dylib                   0x00000001a9c0e63c _dispatch_block_async_invoke2 + 148
	17  libdispatch.dylib                   0x00000001a9bff504 _dispatch_client_callout + 20
	18  libdispatch.dylib                   0x00000001a9c02994 _dispatch_continuation_pop + 504
	19  libdispatch.dylib                   0x00000001a9c01ffc _dispatch_async_redirect_invoke + 584
	20  libdispatch.dylib                   0x00000001a9c10f94 _dispatch_root_queue_drain + 396
	21  libdispatch.dylib                   0x00000001a9c117c0 _dispatch_worker_thread2 + 164
	22  libsystem_pthread.dylib             0x00000001a9d820c4 _pthread_wqthread + 228
	23  libsystem_pthread.dylib             0x00000001a9d80e20 start_wqthread + 8
)
```

### LINKED ISSUE #64: Ventura - cannot select encrypt/sign icons
Before, and after typing the email of someone with a gpg public key in my keychain (E.g sending to myself), the icons to select encrypt/sign are unavailable 

Screenshot 2022-10-21 at 11 08 20

### LINKED ISSUE #65: Ventura - sending encrypted generates error in key lookup, but ultimately works.
In ventura `13.0 (22A379)` select all three options 

Screenshot 2022-10-21 at 11 10 18

Then compose an email (note that https://github.com/Free-GPGMail/Free-GPGMail/issues/64 happens, cannot select the encrypt icon, but that's ok cause its now pre selected).  

Screenshot 2022-10-21 at 11 10 34

Type the recipient, subject and body - note recipient is someone with a public key in my keychain (me, sending to me) 

Attempt to send

See message:

Screenshot 2022-10-21 at 11 10 29

Click OK

Ultimately the email is sent correctly.

And when received is encrypted and signed, even though the warning said it would be sent without encryption

Screenshot 2022-10-21 at 11 13 19

### LINKED ISSUE #67: Support for GPG Mail 7
Hi, 

Is there any eta or working guide for GPG Mail 7? As it could improve issues such as #64 and #65

### PR DESCRIPTION
**Pull request by bnavigator**
2022.2 brings only a slightly modified version of the GPGMail_6 folder as new GPGMail_7 for compatibility with Ventura. Applying the same liberation approach to the SupportPlanManager as on previous versions.

Fixes #67 #65 #64 #63

### CODE REVIEW

**Comment by bnavigator** [comment]
Please test: [Free-GPGMail_7_2022.2b1.mailbundle.zip](https://github.com/Free-GPGMail/Free-GPGMail/files/9975410/Free-GPGMail_7_2022.2b1.mailbundle.zip)

Ping @PhilETaylor

**Comment by PhilETaylor** [comment]
> Ping @PhilETaylor

in bed, will look first thing in the morning :) thanks.

**Comment by skj804** [comment]
For me, it does work for Ventura 13.0. Many thanks,

**Comment by AwlsomeAlex** [comment]
Works for me on Ventura 13.0.1. Will do some additional testing.

**Comment by andatche** [comment]
Works nicely for me on 13.0.1. Thanks!

**Comment by bnavigator** [comment]
Thanks for testing. I'll cut a new release later.

**Pull request merged**
