### PR TITLE
Update source code to v2023.2

### PR DESCRIPTION
**Pull request by mattcen**
This code is direct from GPGTools.org, without customizations, so still requires find/replace for GPGMail -> Free-GPGMail etc.

For the record, I did the following:

```bash
cd Source
rm -rf */
curl https://releases.gpgtools.com/GPG_Suite-2023.2.txz | \
  tar xJ --wildcards 'GPGMail_?' Libmacgpg
```

### CODE REVIEW

**Comment by bnavigator** [comment]
The correct workflow is to change the unchanged source in the `unchanged-source` branch and then merge `master` into it.

**Comment by mattcen** [comment]
Ah, right; thanks; will fix.

**Comment by bnavigator** [comment]
There does not seem to be any change in the downloadable 2023.2 sources.

They mark their CompytibilityUUIDs in the GPG Mail Loader, not the plugins themselves.

**Comment by bnavigator** [comment]
Closing, as the sources of v2023.2 do not contain any changes for GPGMail_* and Libmacgpg.

**Comment by mattcen** [comment]
OK, that makes sense, but I suspect it's also worth updating the tag/release to 2023.2 for clarity, and closing #84, right?

**Comment by mattcen** [comment]
Ah, you beat me to the latter.

**Comment by bnavigator** [comment]
Done with the former, too.

**Pull request closed without merging**
